spring.application.name=circulo-verde

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3309/circuloverde2}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

sativum.token=${SATIVUM_TOKEN:eyJvcmciOiI2NTVmNzExNDc0N2I4OTAwMDE4NDIyMTQiLCJpZCI6Ijg4MjIxMWI4ZWIxZjQyODI5N2ZmYWJmNDZjNTlhMzIxIiwiaCI6Im11cm11cjEyOCJ9}
weather.api.key=${WEATHER_API_KEY:6a9235f1d723a811a3f69e3d791e71d7}
aemet.api.key=${AEMET_API_KEY:SIN_CLAVE}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

logging.level.root=WARN
logging.level.com.circuloverde=INFO
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=WARN

spring.thymeleaf.cache=true
